<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-07 15:51
=======
# Generated by Django 4.2.4 on 2023-09-12 04:54
>>>>>>> origin/Schienenlogistig-v2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('kunden', '0001_initial'),
        ('trainer', '0001_initial'),
        ('pit', '0012_remove_ansprechpartner_kunde_and_more'),
=======
        ('pit', '0012_remove_ansprechpartner_kunde_and_more'),
        ('kunden', '0001_initial'),
        ('trainer', '0001_initial'),
>>>>>>> origin/Schienenlogistig-v2
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_nummer', models.IntegerField(unique=True)),
                ('thema', models.CharField(default='Outlook', max_length=50)),
                ('kurs_start', models.DateTimeField(blank=True, null=True)),
                ('kurs_ende', models.DateTimeField(blank=True, null=True)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='kunden.kunde')),
                ('schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.schiene')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.server')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='trainer.trainer')),
            ],
        ),
    ]
