# Generated by Django 5.0.2 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='Hardware_Status',
            field=models.CharField(choices=[('Ohne HW', 'Ohne HW'), ('mit HW', 'mit HW'), ('HW vo Ort', 'HW vo Ort'), ('Rückholung', 'Rückholung')], default='mit HW', max_length=255),
        ),
    ]
