# Generated by Django 5.0.2 on 2024-02-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurse', '0002_kurs_hardware_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='Hardware_Status',
            field=models.CharField(choices=[('Ohne HW', 'Ohne HW'), ('mit HW', 'mit HW'), ('HW vor Ort', 'HW vor Ort'), ('Rückholung', 'Rückholung')], default='mit HW', max_length=255),
        ),
    ]
