# Generated by Django 4.2.4 on 2023-09-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='land',
        ),
    ]
