<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-07 15:51
=======
# Generated by Django 4.2.4 on 2023-09-12 04:54
>>>>>>> origin/Schienenlogistig-v2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Telefon', models.CharField(blank=True, max_length=17, null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.adresse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
