# Generated by Django 4.2.4 on 2023-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Vorname', models.CharField(blank=True, max_length=100, null=True)),
                ('Outlook', models.BooleanField(default=False)),
                ('SharePoint', models.BooleanField(default=False)),
                ('SMS', models.BooleanField(default=False)),
                ('Mobil', models.CharField(blank=True, max_length=17, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
