# Generated by Django 4.2.4 on 2023-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Telefon',
            new_name='Mobil',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Outlook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='SMS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='SharePoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Vorname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
