# Generated by Django 4.2.4 on 2023-09-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UebersichtsTabelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von_datum', models.DateField(auto_now_add=True)),
                ('bis_datum', models.DateField(auto_now_add=True)),
                ('beschreibung', models.TextField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurse.kurs')),
            ],
        ),
    ]
