# Generated by Django 5.0.1 on 2024-02-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0002_remove_adresse_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('Firma', 'Firma'), ('Behörde', 'Behörde')], max_length=255)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anrede', models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], default='Herr', max_length=255)),
                ('vorname', models.CharField(max_length=255, null=True)),
                ('nachname', models.CharField(default='Müller/Meier/Schmitz', max_length=255)),
                ('Telefon', models.CharField(blank=True, max_length=17, null=True)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ansprechpartner', to='kunden.kunde')),
            ],
        ),
    ]
