# Generated by Django 5.0.2 on 2024-02-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0001_initial'),
        ('start', '0002_remove_adresse_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='adresse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.adresse'),
        ),
    ]
