# Generated by Django 5.0.1 on 2024-02-06 17:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kunden', '0001_initial'),
        ('kurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestplattenImageNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FestplattenImageServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Imagen', 'Imagen'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung'), ('Selbstabholung', 'Selbstabholung')], max_length=255)),
                ('DruckerFuellstand', models.IntegerField(default=100)),
                ('Nighthawk', models.CharField(default='Beispiel: NH 01', max_length=10)),
                ('Bemerkung', models.TextField(default='Fehler/Bemerkung', max_length=500)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pit.festplattenimagenotebook')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung'), ('Selbstabholung', 'Selbstabholung')], default='Zurücksetzen', max_length=255)),
                ('Bemerkung', models.TextField(default='Fehler/Bemerkung', max_length=500)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pit.festplattenimageserver')),
            ],
        ),
        migrations.CreateModel(
            name='Rueckholung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RueckDatum', models.DateField(blank=True, null=True)),
                ('Kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('VA_Nummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurse.kurs')),
                ('Schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.schiene')),
                ('Server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.server')),
            ],
        ),
        migrations.CreateModel(
            name='Abholung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VA_Nummer', models.IntegerField(unique=True)),
                ('Name', models.CharField(default='Mustermann', max_length=255)),
                ('Vorname', models.CharField(default='Max', max_length=255)),
                ('Name2', models.CharField(blank=True, max_length=255, null=True)),
                ('Vorname2', models.CharField(blank=True, max_length=255, null=True)),
                ('Mobile1', models.CharField(default='+49 123 456 7890', max_length=17)),
                ('Mobile2', models.CharField(blank=True, max_length=17, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Firmenwagen', models.CharField(choices=[('Ja', 'Ja'), ('Privat Fahrzeug', 'Privat Fahrzeug'), ('Mietfahrzeug', 'Mietfahrzeug')], max_length=255)),
                ('Fahrzeugvermieter', models.CharField(blank=True, max_length=255, null=True)),
                ('Fahrzeug_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Kennzeichen', models.CharField(default='K-ML xyz', max_length=255)),
                ('Datum', models.DateField(blank=True, null=True)),
                ('Tourdaten', ckeditor.fields.RichTextField(blank=True, max_length=4900, null=True)),
                ('status', models.CharField(choices=[('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung')], default='Weiterleitung', max_length=255)),
                ('Kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('Schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.schiene')),
                ('Server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.server')),
            ],
        ),
        migrations.CreateModel(
            name='Versand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField(blank=True, null=True)),
                ('Kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('Schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.schiene')),
                ('Server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.server')),
                ('VA_Nummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurse.kurs')),
            ],
        ),
    ]
