# Generated by Django 4.2.4 on 2023-09-26 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abholung',
            name='Tourdaten',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4900, null=True),
        ),
    ]
