# Generated by Django 4.2.4 on 2023-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schiene',
            name='druckerfuellstand',
        ),
        migrations.AddField(
            model_name='schiene',
            name='DruckerFuellstandA',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='schiene',
            name='DruckerFuellstandB',
            field=models.IntegerField(default=100),
        ),
    ]
