# Generated by Django 4.2.4 on 2023-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestplattenImageServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FestplattenImageWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FestplattenImage',
            new_name='FestplattenImageNotebook',
        ),
        migrations.AddField(
            model_name='schienebewegung',
            name='dpd_beauftragt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schienebewegung',
            name='dpd_beauftragt_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schienebewegung',
            name='geloescht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schienebewegung',
            name='geloescht_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
