# Generated by Django 5.0.2 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schiene',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Imagen', 'Imagen'), ('Reserviert', 'Reserviert'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung'), ('Selbstabholung', 'Selbstabholung')], max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Reserviert', 'Reserviert'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung'), ('Selbstabholung', 'Selbstabholung')], default='Zurücksetzen', max_length=255),
        ),
    ]
