# Generated by Django 4.2.4 on 2023-08-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0002_festplattenimageserver_festplattenimageworkstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schienebewegung',
            name='geloescht',
        ),
        migrations.RemoveField(
            model_name='schienebewegung',
            name='geloescht_datum',
        ),
    ]
