# Generated by Django 4.2.4 on 2023-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0002_remove_schiene_druckerfuellstand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schiene',
            name='Bemerkung',
            field=models.TextField(default='Fehler/Bemerkung', max_length=500),
        ),
        migrations.AddField(
            model_name='schiene',
            name='Nighthawk',
            field=models.CharField(default='Beispiel: NH 01', max_length=10),
        ),
        migrations.AlterField(
            model_name='schiene',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Imagen', 'Imagen')], max_length=255),
        ),
    ]
