# Generated by Django 5.0.1 on 2024-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0002_alter_abholung_tourdaten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schiene',
            old_name='DruckerFuellstandA',
            new_name='DruckerFuellstand',
        ),
        migrations.RemoveField(
            model_name='schiene',
            name='DruckerFuellstandB',
        ),
    ]
