# Generated by Django 4.2.4 on 2023-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0003_schiene_bemerkung_schiene_nighthawk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='image',
        ),
        migrations.RemoveField(
            model_name='server',
            name='kurs',
        ),
        migrations.AddField(
            model_name='server',
            name='Bemerkung',
            field=models.TextField(default='Fehler/Bemerkung', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen')], default='Zurücksetzen', max_length=255),
        ),
    ]
