# Generated by Django 4.2.4 on 2023-08-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0003_remove_schienebewegung_geloescht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schienebewegung',
            name='ziel_adresse',
        ),
    ]
