# Generated by Django 5.0.1 on 2024-02-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0001_initial'),
        ('pit', '0003_rename_druckerfuellstanda_schiene_druckerfuellstand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schiene',
            name='datum_kms_aktivierung',
        ),
        migrations.AlterField(
            model_name='abholung',
            name='VA_Nummer',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Versand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField(blank=True, null=True)),
                ('VA_Nummer', models.IntegerField(max_length=8, unique=True)),
                ('Kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('Schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.schiene')),
                ('Server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.server')),
            ],
        ),
    ]
