# Generated by Django 4.2.4 on 2023-08-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0004_remove_schienebewegung_ziel_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schienebewegung',
            name='weiterleitung_adresse',
        ),
    ]
