# Generated by Django 4.2.4 on 2023-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0004_remove_server_image_remove_server_kurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Unbekannt', 'Unbekannt')], default='Zurücksetzen', max_length=255),
        ),
    ]
