# Generated by Django 5.0.1 on 2024-02-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurse', '0002_remove_kurs_schiene_remove_kurs_server'),
        ('pit', '0004_remove_schiene_datum_kms_aktivierung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abholung',
            name='VA_Nummer',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='versand',
            name='VA_Nummer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurse.kurs'),
        ),
    ]
