# Generated by Django 4.2.4 on 2023-08-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0005_remove_schienebewegung_weiterleitung_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='kurz_art',
        ),
        migrations.AddField(
            model_name='kurs',
            name='kurs_ende',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurs',
            name='kurs_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kurs',
            name='schiene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.schiene'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.server'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='thema',
            field=models.CharField(default='Outlook', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Telefon',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='kunde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.kunde'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='pit.trainer'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='va_nummer',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anrede', models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], default='Herr', max_length=255)),
                ('Telefon', models.CharField(blank=True, max_length=17, null=True)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ansprechpartner', to='pit.kunde')),
            ],
        ),
    ]
