# Generated by Django 5.0.1 on 2024-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0001_initial'),
        ('kurse', '0002_remove_kurs_schiene_remove_kurs_server'),
        ('pit', '0005_alter_abholung_va_nummer_alter_versand_va_nummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rueckholung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RueckDatum', models.DateField(blank=True, null=True)),
                ('Kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('Schiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.schiene')),
                ('Server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pit.server')),
                ('VA_Nummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurse.kurs')),
            ],
        ),
    ]
