# Generated by Django 4.2.4 on 2023-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0006_remove_kurs_kurz_art_kurs_kurs_ende_kurs_kurs_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansprechpartner',
            name='nachname',
            field=models.CharField(default='Müller/Meier/Schmitz', max_length=255),
        ),
        migrations.AddField(
            model_name='ansprechpartner',
            name='vorname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
