# Generated by Django 4.2.4 on 2023-09-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0007_ansprechpartner_nachname_ansprechpartner_vorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pit.festplattenimageserver'),
        ),
    ]
