# Generated by Django 4.2.4 on 2023-09-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0008_server_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pit.festplattenimageserver'),
        ),
    ]
