# Generated by Django 4.2.4 on 2023-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0010_alter_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schienebewegung',
            name='kalenderwoche',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
