# Generated by Django 4.2.4 on 2023-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0011_schienebewegung_kalenderwoche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansprechpartner',
            name='kunde',
        ),
        migrations.DeleteModel(
            name='FestplattenImageWorkstation',
        ),
        migrations.RemoveField(
            model_name='kunde',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='schiene',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='server',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='schienebewegung',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='schienebewegung',
            name='schiene',
        ),
        migrations.RemoveField(
            model_name='schienebewegung',
            name='weiterleitung_kunde',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='schiene',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Imagen', 'Imagen'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung')], max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Lager', 'Lager'), ('Unterwegs', 'Unterwegs'), ('Zurücksetzen', 'Zurücksetzen'), ('Versand', 'Versand'), ('Standort', 'Standort'), ('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung')], default='Zurücksetzen', max_length=255),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Ansprechpartner',
        ),
        migrations.DeleteModel(
            name='Kunde',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='SchieneBewegung',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
