# Generated by Django 4.2.4 on 2023-09-13 08:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0013_alter_schiene_status_alter_server_status_abholung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abholung',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='abholung',
            name='Kennzeichen',
            field=models.CharField(default='K-ML xyz', max_length=255),
        ),
        migrations.AddField(
            model_name='abholung',
            name='Mobile1',
            field=models.CharField(default='+49 123 456 7890', max_length=17),
        ),
        migrations.AddField(
            model_name='abholung',
            name='Mobile2',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='abholung',
            name='Tourdaten',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='abholung',
            name='Firmenwagen',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Privat Fahrzeug', 'Privat Fahrzeug')], max_length=255),
        ),
        migrations.AlterField(
            model_name='abholung',
            name='Name',
            field=models.CharField(default='Mustermann', max_length=255),
        ),
        migrations.AlterField(
            model_name='abholung',
            name='Vorname',
            field=models.CharField(default='Max', max_length=255),
        ),
    ]
