# Generated by Django 4.2.4 on 2023-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0014_remove_abholung_mobile_abholung_kennzeichen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abholung',
            name='status',
            field=models.CharField(choices=[('Rückholung', 'Rückholung'), ('Weiterleitung', 'Weiterleitung')], default='Weiterleitung', max_length=255),
        ),
    ]
