# Generated by Django 4.2.4 on 2023-09-13 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0015_abholung_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abholung',
            name='Tourdaten',
            field=ckeditor.fields.RichTextField(blank=True, max_length=900, null=True),
        ),
    ]
