# Generated by Django 4.2.4 on 2023-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0017_abholung_fahrzeug_type_abholung_name2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abholung',
            name='Fahrzeugvermieter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
