# Generated by Django 4.2.4 on 2023-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postit',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
